@php $query = $this->exportQuery(); @endphp

<div>
    <div class="mb-6">
        <h1 class="text-2xl font-bold tracking-tight text-gray-900">Reports</h1>
        <p class="mt-1 text-sm text-gray-600">
            Choose a date range, then download any report as a spreadsheet (CSV) or a
            printable document (PDF). Every report you generate is recorded below.
        </p>
    </div>

    {{-- Date range, applied to every report --}}
    <div class="card mb-6 p-4">
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div>
                <label for="from" class="label">From</label>
                <input id="from" type="date" wire:model.live="from" class="input mt-1">
            </div>
            <div>
                <label for="to" class="label">To</label>
                <input id="to" type="date" wire:model.live="to" class="input mt-1">
            </div>
            <div class="flex items-end gap-2 sm:col-span-2">
                <button type="button" wire:click="useLastYear" class="btn-secondary">Last 12 months</button>
                @if ($from !== '' || $to !== '')
                    <button type="button" wire:click="clearRange" class="btn-secondary">Clear</button>
                @endif
            </div>
        </div>

        <p class="mt-3 text-xs text-gray-500">
            Leave both dates empty to cover all records. The range you choose is saved with
            the report, so anyone can see exactly what was included.
        </p>
    </div>

    {{-- The reports --}}
    <div class="grid gap-4 sm:grid-cols-2">
        @foreach ($this->reports as $report)
            <div class="card flex flex-col p-5">
                <h2 class="text-base font-semibold text-gray-900">{{ $report->title() }}</h2>
                <p class="mt-1 flex-1 text-sm text-gray-600">{{ $report->description() }}</p>

                <div class="mt-4 flex flex-wrap gap-2">
                    <a href="{{ route('reports.csv', $report->key()).($query ? '?'.$query : '') }}"
                       class="btn-secondary">
                        Download CSV
                    </a>
                    <a href="{{ route('reports.pdf', $report->key()).($query ? '?'.$query : '') }}"
                       class="btn-primary">
                        Download PDF
                    </a>
                </div>
            </div>
        @endforeach
    </div>

    {{-- Audit trail --}}
    <div class="card mt-8 overflow-hidden">
        <div class="border-b border-gray-200 p-5">
            <h2 class="text-base font-semibold text-gray-900">Report History</h2>
            <p class="mt-1 text-sm text-gray-600">
                Every report generated, who ran it, and exactly which filters were used.
            </p>
        </div>

        @if ($this->history->isEmpty())
            <div class="p-10 text-center">
                <p class="text-sm font-medium text-gray-900">No reports have been generated yet</p>
                <p class="mt-1 text-sm text-gray-600">Download one above and it will appear here.</p>
            </div>
        @else
            <div class="overflow-x-auto">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            @foreach (['Report', 'Format', 'Rows', 'Filters Used', 'Generated By', 'When'] as $heading)
                                <th scope="col" class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-600">
                                    {{ $heading }}
                                </th>
                            @endforeach
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-200 bg-white">
                        @foreach ($this->history as $entry)
                            <tr class="hover:bg-gray-50">
                                <td class="px-4 py-3 text-sm font-medium text-gray-900">
                                    {{ Str::headline($entry->report_type) }}
                                </td>
                                <td class="px-4 py-3">
                                    <span class="badge bg-gray-100 text-gray-700 ring-gray-500/20">
                                        {{ strtoupper($entry->format ?? '—') }}
                                    </span>
                                </td>
                                <td class="px-4 py-3 text-sm text-gray-600">{{ number_format((int) $entry->row_count) }}</td>
                                <td class="px-4 py-3 text-xs text-gray-600">
                                    @if (empty($entry->parameters))
                                        <span class="text-gray-400">No filters (all records)</span>
                                    @else
                                        @foreach ($entry->parameters as $key => $value)
                                            @if ($value !== null && $value !== '')
                                                <span class="mr-1 inline-block rounded bg-gray-100 px-1.5 py-0.5">
                                                    {{ Str::headline($key) }}: {{ is_array($value) ? implode(', ', $value) : $value }}
                                                </span>
                                            @endif
                                        @endforeach
                                    @endif
                                </td>
                                <td class="px-4 py-3 text-sm text-gray-600">
                                    {{ $entry->generatedBy?->full_name ?? 'Deleted account' }}
                                </td>
                                <td class="whitespace-nowrap px-4 py-3 text-sm text-gray-600">
                                    {{ $entry->generated_at->format('j M Y, g:i a') }}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

            <div class="border-t border-gray-200 p-4">{{ $this->history->links() }}</div>
        @endif
    </div>
</div>
