@php $query = $this->exportQuery(); @endphp

<div>
    <div class="mb-10">
        <h1 class="text-[34px] font-semibold tracking-[-0.022em] leading-[1.12] text-foreground">Reports</h1>
        <p class="mt-3 text-[17px] leading-relaxed text-muted-foreground">
            Choose a date range, then download any report as a spreadsheet (CSV) or a
            printable document (PDF). Every report you generate is recorded below.
        </p>
    </div>

    {{-- Date range, applied to every report --}}
    <div class="card mb-10 p-6">
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div>
                <label for="from" class="label">From</label>
                <input id="from" type="date" wire:model.live="from" class="input mt-1">
            </div>
            <div>
                <label for="to" class="label">To</label>
                <input id="to" type="date" wire:model.live="to" class="input mt-1">
            </div>
            <div class="flex items-end gap-2 sm:col-span-2">
                <button type="button" wire:click="useLastYear" class="btn-secondary">Last 12 months</button>
                @if ($from !== '' || $to !== '')
                    <button type="button" wire:click="clearRange" class="btn-secondary">Clear</button>
                @endif
            </div>
        </div>

        <p class="mt-3 text-xs text-muted-foreground">
            Leave both dates empty to cover all records. The range you choose is saved with
            the report, so anyone can see exactly what was included.
        </p>
    </div>

    {{-- The reports --}}
    <div class="grid gap-4 sm:grid-cols-2">
        @foreach ($this->reports as $report)
            <div class="card flex flex-col p-5">
                <h2 class="text-[21px] font-semibold tracking-[-0.01em] leading-[1.25] text-foreground">{{ $report->title() }}</h2>
                <p class="mt-1 flex-1 text-sm text-muted-foreground">{{ $report->description() }}</p>

                <div class="mt-4 flex flex-wrap gap-2">
                    <a href="{{ route('reports.csv', $report->key()).($query ? '?'.$query : '') }}"
                       class="btn-secondary">
                        Download CSV
                    </a>
                    <a href="{{ route('reports.pdf', $report->key()).($query ? '?'.$query : '') }}"
                       class="btn-primary">
                        Download PDF
                    </a>
                </div>
            </div>
        @endforeach
    </div>

    {{-- Audit trail --}}
    <div class="card mt-8 overflow-hidden">
        <div class="border-b border-border p-5">
            <h2 class="text-[21px] font-semibold tracking-[-0.01em] leading-[1.25] text-foreground">Report History</h2>
            <p class="mt-3 text-[17px] leading-relaxed text-muted-foreground">
                Every report generated, who ran it, and exactly which filters were used.
            </p>
        </div>

        @if ($this->history->isEmpty())
            <div class="p-10 text-center">
                <p class="text-sm font-medium text-foreground">No reports have been generated yet</p>
                <p class="mt-3 text-[17px] leading-relaxed text-muted-foreground">Download one above and it will appear here.</p>
            </div>
        @else
            <div class="overflow-x-auto">
                <table class="min-w-full divide-y divide-border">
                    <thead class="bg-muted">
                        <tr>
                            @foreach (['Report', 'Format', 'Rows', 'Filters Used', 'Generated By', 'When'] as $heading)
                                <th scope="col" class="px-6 py-4 text-left text-[12px] font-medium uppercase tracking-[0.06em] text-muted-foreground">
                                    {{ $heading }}
                                </th>
                            @endforeach
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-border bg-card">
                        @foreach ($this->history as $entry)
                            <tr class="group row-hover">
                                <td class="px-6 py-4 text-sm font-medium text-foreground">
                                    {{ Str::headline($entry->report_type) }}
                                </td>
                                <td class="px-6 py-4">
                                    <span class="badge bg-background text-muted-foreground ring-border">
                                        {{ strtoupper($entry->format ?? '—') }}
                                    </span>
                                </td>
                                <td class="px-6 py-4 text-sm text-muted-foreground">{{ number_format((int) $entry->row_count) }}</td>
                                <td class="px-6 py-4 text-xs text-muted-foreground">
                                    @if (empty($entry->parameters))
                                        <span class="text-muted-foreground">No filters (all records)</span>
                                    @else
                                        @foreach ($entry->parameters as $key => $value)
                                            @if ($value !== null && $value !== '')
                                                <span class="mr-1 inline-block rounded bg-background px-1.5 py-0.5">
                                                    {{ Str::headline($key) }}: {{ is_array($value) ? implode(', ', $value) : $value }}
                                                </span>
                                            @endif
                                        @endforeach
                                    @endif
                                </td>
                                <td class="px-6 py-4 text-sm text-muted-foreground">
                                    {{ $entry->generatedBy?->full_name ?? 'Deleted account' }}
                                </td>
                                <td class="whitespace-nowrap px-6 py-4 text-sm text-muted-foreground">
                                    {{ $entry->generated_at->format('j M Y, g:i a') }}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

            <div class="border-t border-border p-4">{{ $this->history->links() }}</div>
        @endif
    </div>
</div>
